=== amitmca/EducationalMaterial/Html/xml/DTD/emp.dtd
<!ELEMENT hrdept (employee) >
<!ELEMENT employee (name,address,contact)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT address (address1,city,state,pin)>
<!ELEMENT address1 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT contact (email,residence,mobile)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT residence (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

=== amitmca/EducationalMaterial/Html/xml/DTD/external2.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE hrdept PUBLIC "mydtd" "emp.dtd" >
<hrdept>
	<employee>
		<name>
			<fname>Amit</fname>
			<lname>Bhalerao</lname>
		</name>
		<address>
			<address1>Morgoan Road</address1>
			<city>Baramati</city>
			<state>Maharashtra</state>
			<pin>413102</pin>
		</address>
		<contact>
			<email>once_amit1@rediffmail.com</email>
			<residence>225209</residence>
			<mobile>9730163853</mobile>
		</contact>
	</employee>	
</hrdept>
